import os,shutil,glob

os.rmdir('CVT')
os.rmdir('DTCWT')
os.rmdir('DTMDCT')
os.rmdir('FPDE')
os.rmdir('GFF')
os.rmdir('GTF')
os.rmdir('HMSD')
os.rmdir('LEPLC')
os.rmdir('LP')
os.rmdir('LPSR')
os.rmdir('MSVD')
os.rmdir('NSCT')
os.rmdir('OIPCNN')
os.rmdir('RP')
os.rmdir('Wavelet')